meta_product_name: "TATTU APP"
meta_title: "Find your ideal tattoo. Seamlessly."
meta_description: "Search through a huge variety of artists and tattoos to find the one that best matches your personality. Easy."
meta_image: "banner-image2.jpg"
twitter_account: "@tattu_app"
